on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string


jobs:
    hello_job:
      runs-on: ubuntu-latest
      steps:
        - name: Hello
          uses: ./.github/actions/hello
          with:
            message: ${{ inputs.message }}